matrix:
  platform:
  - win64,windows
  - linux64,linux,release
  python:
  - 27
  - 35


branch_patterns:
- master
- fb-.*


display_name: "[py{python}] [{branch}] {name} {platform}"


branch-fb-.*:notify_stash:


git:
    reference: "$WORKSPACE/../../Shared/ref_repos/{name}"


additional_repositories:
- git:
    url: "ssh://git@eden.fln.esss.com.br:7999/esss/eden.git"
    branch: "master"
    reference: "$WORKSPACE/../../Shared/ref_repos/eden"

console_color:

junit_patterns:
- "**/build/tests/*.xml"


timeout: 5


label_expression: "{platform} && !12.0"


platform-windows:build_batch_commands:
- |
    set CONDA_PY={python}
    subst /D K:
    subst K: "%WORKSPACE%"
    if not "%ERRORLEVEL%" == "0" exit /B 1
    set PLATFORM={platform}
    set CONDA_FORCE_32BIT=
    set ESSS_DEBUG=
    for /F %%i in ('conda info --root') do set CONDA_ROOT=%%i
    if "%CONDA_PY%" == "35" (
        copy "%CONDA_ROOT%\.condarc-py3.yml" "%WORKSPACE%\.condarc"
    ) else (
        copy "%CONDA_ROOT%\.condarc-py2.yml" "%WORKSPACE%\.condarc"
    )
    set CONDARC=%WORKSPACE%\.condarc
    call conda clean --lock
    cd /d K:\{name}
    call conda info
    call conda install conda-devenv
    call conda devenv --prune -n {name}-py{python}
    call activate {name}-py{python}
    call conda list
    py.test -l --junit-xml=K:/{name}/build/tests/{name}-pytest.xml


platform-linux:build_shell_commands:
- |
    export CONDA_PY={python}
    $WORKSPACE/eden/bin/run-chroot-command bash -c "
        export PATH=$HOME/Work/miniconda/bin:$PATH
        cd $WORKSPACE/{name}
        if [ "$CONDA_PY" == "35" ]; then
            cp "$(conda info --root)/.condarc-py3.yml" "$WORKSPACE/.condarc"
        else
            cp "$(conda info --root)/.condarc-py2.yml" "$WORKSPACE/.condarc"
        fi
        export CONDARC=$WORKSPACE/.condarc
        conda info
        conda install conda-devenv
        conda devenv --prune -n {name}-py{python}
        source activate {name}-py{python}
        conda list
        py.test -l --junit-xml=$WORKSPACE/{name}/build/tests/{name}-pytest.xml
    "
