repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: rst
        name: rst
        entry: rst-lint --encoding utf-8
        files: CHANGELOG.rst
        language: python
        additional_dependencies: [pygments, restructuredtext_lint]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        files: src
        args: []
        additional_dependencies: [pytest, types-mock, types-pyyaml]
