name: deps

dependencies:
  - click
  - colorama
  - mock <2
  - pytest-mock
  - jinja2
  - pyyaml
  - future

environment:
  - PYTHONPATH:
    - {{ os.path.join(root, 'source', 'python') }}

  - PATH:
    - {{ os.path.join(root, 'bin') }}
