name: deps

dependencies:
  - click
  - colorama
  - future
  - jinja2
  - pre-commit
  - pytest >=5
  - pytest-mock
  - python >=3.6,<3.8
  - pyyaml

environment:
  PYTHONPATH:
    - {{ os.path.join(root, 'source', 'python') }}

  PATH:
    - {{ os.path.join(root, 'bin') }}
