name: deps

dependencies:
  - python >=3.6
  - click
  - colorama
  - pytest >=5
  - pytest-mock
  - jinja2
  - pyyaml
  - future

environment:
  PYTHONPATH:
    - {{ os.path.join(root, 'source', 'python') }}

  PATH:
    - {{ os.path.join(root, 'bin') }}
