{% set PY2 = os.environ.get('CONDA_PY', '27') < '35' %}
{% set PY3 = not PY2 %}
name: deps

dependencies:
  - click
  - colorama
  - mock <2
  - pytest-mock
  - jinja2
  - pyyaml
  - future
  - python {{'<3' if PY2 else '>=3'}}

environment:
  - PYTHONPATH:
    - {{ os.path.join(root, 'source', 'python') }}

  - PATH:
    - {{ os.path.join(root, 'bin') }}
