name: test

on:
  push:
    branches:
    - "master"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: "3.10"
        conda-channels: anaconda, conda-forge

    - name: conda-devenv
      run: |
        conda install conda-devenv --quiet
        conda devenv  --quiet

    - name: Test (Linux)
      if: ${{ runner.os == 'Linux' }}
      run: |
        source activate deps
        python -m pytest source/python

    - name: Test (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: cmd
      run: |
        activate deps
        python -m pytest source/python
