name: test

on:
  push:
    branches:
    - "master"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  UV_LOCKED: "1"

jobs:

  test:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Test
      run: |
        uv run pytest
        uv run deps --help
    - name: Test Build
      shell: bash
      run: |
        uv build
        uvx --with `find dist/*.whl` deps --help
